### ISSUE TITLE
Please write in readme which dependancies (libs) do you use.

### ISSUE THREAD

**Issue by Rainer-Lang** [ffgiraldez/rx-mvvm-android#1]

**Comment by ffgiraldez** [comment]
the dependencies can be checked here [build.gradle](https://github.com/ffgiraldez/rx-mvvm-android/blob/master/app/build.gradle), so i won't add it until finish other features, actually working on the persistence layer, when compleded i will add dependencies into README, please be patient and check build.gradle file until that

**Comment by zuoer8676** [comment]
test study
