### ISSUE TITLE
RecyclerView.bindResults parameter name check please

### ISSUE THREAD

**Issue by pjshin3** [ffgiraldez/rx-mvvm-android#31]
hello ,
While I was looking at your app source, 
I registered an issue because the name of the parameter seemed to be strange.

RecyclerView.bindResults(error: List<Volume>) Unit = with(adapter as QueryVolumeAdapter)

I think the other name would be better because the item exists...

**Comment by ffgiraldez** [comment]
yes, totally right, it should be `volumeList`, `results` or something similar that point you the update of the RecyclerView content, I'm open to PRs, I miss that, and will update during incoming changes I have in the backlog
