### ISSUE TITLE
Databinding used in include the merge the above layout, how to use

### ISSUE THREAD

**Issue by junyao-yu** [ffgiraldez/rx-mvvm-android#5]
Databinding used in include the merge the above layout, how to use

**Comment by ffgiraldez** [comment]
could you explain a bit more? which layout are you talking about?

**Comment by iamthevoid** [comment]
For example: I use same layout inside three other layouts (merge). In this layout i must pass DataBinding data from parent layout. Is this possible? What should i do?

**Comment by ffgiraldez** [comment]
@iamthevoid  @junyao-yu this question it's not related to this project and in order to use data binding and merge layout I can only refer you to [oficial doc](https://developer.android.com/topic/libraries/data-binding/index.html#includes) sorry.
